# Generated by Django 5.1.4 on 2024-12-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_sitio', '0002_alter_post_options_post_author_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='/static/mi_sitio/images/default_post.webp', max_length=500),
        ),
    ]
