# Generated by Django 5.1.4 on 2025-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_sitio', '0003_alter_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default='/static/mi_sitio/images/default_project.webp', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='mi_sitio.technology'),
        ),
    ]
