# Generated by Django 5.1.4 on 2025-01-11 02:10

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_sitio', '0004_technology_project_image_url_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='Contenido en MarkDown'),
        ),
    ]
